application: gaeexamples
version: 0-0-2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.svn(/.*)?$
- ^(.*/)?.*\.git(/.*)?$
- ^(.*/)?vendor/.*